### ISSUE TITLE
Node describe fail and crash

### ISSUE THREAD

**Issue by rabin-io** [RedHatQE/must-gather-explorer#34]
Tried with:
```
Command: describe
Please pass the resource Kind

Command: describe node

Command: describe node ci-op-h11cvbt5-d01fe-tdtrz-worker-westus-xhg5w
```

e.g
```
Command: get node  
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ NAMESPACE ┃ NAME                                           ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│           │ ci-op-h11cvbt5-d01fe-tdtrz-master-1            │
│           │ ci-op-h11cvbt5-d01fe-tdtrz-master-2            │
│           │ ci-op-h11cvbt5-d01fe-tdtrz-master-0            │
│           │ ci-op-h11cvbt5-d01fe-tdtrz-worker-westus-lkhtr │
│           │ ci-op-h11cvbt5-d01fe-tdtrz-worker-westus-d4x76 │
│           │ ci-op-h11cvbt5-d01fe-tdtrz-worker-westus-xhg5w │
└───────────┴────────────────────────────────────────────────┘
Command: describe node ci-op-h11cvbt5-d01fe-tdtrz-worker-westus-xhg5w
Traceback (most recent call last):
  File "/mnt/data/src/redhat/RedHatQE/must-gather-explorer/app/main.py", line 296, in <module>
    main()
    ~~~~^^
  File "/mnt/data/src/redhat/RedHatQE/must-gather-explorer/.venv/lib64/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/mnt/data/src/redhat/RedHatQE/must-gather-explorer/.venv/lib64/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/mnt/data/src/redhat/RedHatQE/must-gather-explorer/.venv/lib64/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/src/redhat/RedHatQE/must-gather-explorer/.venv/lib64/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/data/src/redhat/RedHatQE/must-gather-explorer/app/main.py", line 193, in main
    actions_dict[action_name](resources_raw_data, print_yaml)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_describe() takes 0 positional arguments but 2 were given
```

**Comment by jpeimer** [comment]
Hi Rabin, thank you for this issue. 
`describe` command is not implemented yet, but you can print the resource yaml with:
`get node <node_name> -oyaml`

**Comment by myakove** [comment]
App do not crush anymore on invalid commands.
